# -*- mode: ruby -*-
# vi: set ft=ruby :

# Vagrantfile API/syntax version. Don't touch unless you know what you're doing!
VAGRANTFILE_API_VERSION = "2"

Vagrant.configure(VAGRANTFILE_API_VERSION) do |config|

  config.vm.define "fedora" do |fedora|
    fedora.vm.box = "fedora-20"
    fedora.vm.box_url = "https://dl.dropboxusercontent.com/u/15733306/vagrant/fedora-20-netinst-2014_01_05-minimal-puppet-guestadditions.box"
    fedora.vm.synced_folder "~/git", "/host_git"
    # fedora.vm.hostname = "fedora"
    # fedora.vm.network :private_network, ip: "192.168.33.10"
    # fedora.vm.network :forwarded_port, guest: 80, host: 8080
    # fedora.vm.network :public_network
    # fedora.vm.provision :shell, :path => "bootstrap_build.sh"
    fedora.vm.provision :puppet do |puppet|
      puppet.manifests_path = "manifests"
      puppet.manifest_file  = "fedora-20.pp"
    end
  end

end
