---
- name: create nginx image
  command: /usr/bin/docker build -t="mockserver/nginx" https://raw.github.com/jamesdbloom/mockserver/master/ci/docker/nginx/Dockerfile

- name: stop any existing nginx container (ignore failure i.e. first run)
  command: /usr/bin/docker stop nginx
  ignore_errors: yes

- name: rm any existing nginx container (ignore failure i.e. first run)
  command: /usr/bin/docker rm nginx
  ignore_errors: yes

- name: run nginx image
  command: /usr/bin/docker run -name nginx -link jenkins:ci -p 80:80 -d mockserver/nginx
